/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package az.com.salesmanagement.controller;

import az.com.salesmanagement.constants.DictionaryEnum;
import az.com.salesmanagement.dao.CustomersDao;
import az.com.salesmanagement.dao.DictionaryDao;
import az.com.salesmanagement.model.Customers;
import az.com.salesmanagement.model.Dictionary;
import java.awt.ComponentOrientation;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vafa
 */
public class CustomerController extends javax.swing.JFrame {

    /**
     * Creates new form CustomerController
     */
    public CustomerController() {
        initComponents();
        addContents();
        addComboData();
//        applyComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customersTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        Voen = new javax.swing.JLabel();
        Type = new javax.swing.JLabel();
        customersVoen = new javax.swing.JTextField();
        customerName = new javax.swing.JTextField();
        customerType = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        customersInsertButton = new javax.swing.JButton();
        customersUpdateButton = new javax.swing.JButton();
        customersDeleteButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        customerNameSearch = new javax.swing.JLabel();
        searchCustomerByVoen = new javax.swing.JTextField();
        searchCustomerByName = new javax.swing.JTextField();
        customerTypeSearch = new javax.swing.JLabel();
        customerVoenSearch = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        searchCustomerByType = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        backButtonFromCustomers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alış-veriş");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(12, 102, 193));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentResized(evt);
            }
        });

        customersTable.setBackground(new java.awt.Color(240, 248, 255));
        customersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Ad", "Vöen", "Tip"
            }
        ));
        customersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customersTable);

        jPanel2.setBackground(new java.awt.Color(12, 102, 193));

        Name.setFont(new java.awt.Font("Nyala", 1, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(240, 248, 255));
        Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name.setText("Ad");

        Voen.setFont(new java.awt.Font("Nyala", 1, 18)); // NOI18N
        Voen.setForeground(new java.awt.Color(240, 248, 255));
        Voen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Voen.setText("Vöen");

        Type.setFont(new java.awt.Font("Nyala", 1, 18)); // NOI18N
        Type.setForeground(new java.awt.Color(240, 248, 255));
        Type.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Type.setText("Tip");

        customersVoen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        customersVoen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersVoenActionPerformed(evt);
            }
        });

        customerName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        customerName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customerNameFocusGained(evt);
            }
        });
        customerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameActionPerformed(evt);
            }
        });

        customerType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        customerType.setForeground(new java.awt.Color(12, 102, 193));
        customerType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customerTypeFocusGained(evt);
            }
        });
        customerType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Voen, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customersVoen)
                    .addComponent(customerName)
                    .addComponent(customerType, 0, 144, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name)
                    .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Voen)
                    .addComponent(customersVoen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Type)
                    .addComponent(customerType, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(12, 102, 193));

        customersInsertButton.setBackground(new java.awt.Color(240, 248, 255));
        customersInsertButton.setFont(new java.awt.Font("Nyala", 1, 24)); // NOI18N
        customersInsertButton.setForeground(new java.awt.Color(12, 102, 193));
        customersInsertButton.setText("Əlavə et");
        customersInsertButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customersInsertButtonMouseClicked(evt);
            }
        });
        customersInsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersInsertButtonActionPerformed(evt);
            }
        });

        customersUpdateButton.setBackground(new java.awt.Color(240, 248, 255));
        customersUpdateButton.setFont(new java.awt.Font("Nyala", 1, 24)); // NOI18N
        customersUpdateButton.setForeground(new java.awt.Color(12, 102, 193));
        customersUpdateButton.setText("Dəyiş");
        customersUpdateButton.setMaximumSize(new java.awt.Dimension(111, 35));
        customersUpdateButton.setMinimumSize(new java.awt.Dimension(111, 35));
        customersUpdateButton.setOpaque(false);
        customersUpdateButton.setPreferredSize(new java.awt.Dimension(111, 35));
        customersUpdateButton.setRequestFocusEnabled(false);
        customersUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersUpdateButtonActionPerformed(evt);
            }
        });

        customersDeleteButton.setBackground(new java.awt.Color(240, 248, 255));
        customersDeleteButton.setFont(new java.awt.Font("Nyala", 1, 24)); // NOI18N
        customersDeleteButton.setForeground(new java.awt.Color(12, 102, 193));
        customersDeleteButton.setText("Sil");
        customersDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customersDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(customersUpdateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(customersInsertButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(customersInsertButton)
                .addGap(18, 18, 18)
                .addComponent(customersUpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(customersDeleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(12, 102, 193));

        customerNameSearch.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        customerNameSearch.setForeground(new java.awt.Color(240, 248, 255));
        customerNameSearch.setText("Ad");

        searchCustomerByVoen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerByVoenActionPerformed(evt);
            }
        });

        customerTypeSearch.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        customerTypeSearch.setForeground(new java.awt.Color(240, 248, 255));
        customerTypeSearch.setText("Tip");

        customerVoenSearch.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        customerVoenSearch.setForeground(new java.awt.Color(240, 248, 255));
        customerVoenSearch.setText("Voen");

        searchButton.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(12, 102, 193));
        searchButton.setText("Axtarın");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });

        searchCustomerByType.setForeground(new java.awt.Color(12, 102, 193));
        searchCustomerByType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchCustomerByTypeFocusGained(evt);
            }
        });
        searchCustomerByType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerByTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(searchButton)
                .addGap(102, 102, 102))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(searchCustomerByName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchCustomerByVoen, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(customerNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(customerVoenSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(customerTypeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchCustomerByType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerVoenSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerTypeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchCustomerByType, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchCustomerByName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchCustomerByVoen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButton)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(240, 248, 255));
        jButton1.setFont(new java.awt.Font("Nyala", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(12, 102, 193));
        jButton1.setText("<-");
        jButton1.setToolTipText("");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        backButtonFromCustomers.setBackground(new java.awt.Color(240, 248, 255));
        backButtonFromCustomers.setFont(new java.awt.Font("Nyala", 1, 18)); // NOI18N
        backButtonFromCustomers.setForeground(new java.awt.Color(12, 102, 193));
        backButtonFromCustomers.setText("Geri");
        backButtonFromCustomers.setToolTipText("");
        backButtonFromCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonFromCustomersMouseClicked(evt);
            }
        });
        backButtonFromCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonFromCustomersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(82, 82, 82))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(31, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(backButtonFromCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(61, 61, 61)))
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(backButtonFromCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void customersVoenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersVoenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customersVoenActionPerformed

    private void customerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameActionPerformed

    private void customersUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersUpdateButtonActionPerformed
        CustomersDao dao=new CustomersDao();
        try {
            dao.updateCustomer(id(), name(), voen(), type());
        } catch (SQLException ex) {
            Logger.getLogger(CustomerController.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel model=(DefaultTableModel)customersTable.getModel();
        model.setRowCount(0);
        addContents();
    }//GEN-LAST:event_customersUpdateButtonActionPerformed

    private void jPanel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentResized

    private void customersInsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersInsertButtonActionPerformed
        CustomersDao dao=new CustomersDao();
        try {
            Customers customer=new Customers();
            customer.setName(name());
            customer.setVoen(voen());
            customer.setType(type());
            dao.addCustomer(customer);
            DefaultTableModel model=(DefaultTableModel)customersTable.getModel();
            model.setRowCount(0);
            addContents();
        } catch (SQLException ex) {
            Logger.getLogger(CustomerController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_customersInsertButtonActionPerformed

    private void customersInsertButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customersInsertButtonMouseClicked
        
    }//GEN-LAST:event_customersInsertButtonMouseClicked

    private void customerNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameFocusGained

    private void customerTypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerTypeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_customerTypeFocusGained

    private void customersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customersTableMouseClicked
        DefaultTableModel model=(DefaultTableModel)customersTable.getModel();
        int row=customersTable.getSelectedRow();
        Integer id=(Integer)model.getValueAt(row, 0);
        String name=(String)model.getValueAt(row, 1);
        String voen=(String)model.getValueAt(row, 2);
        String typeLabel=(String)model.getValueAt(row, 3);
        customerName.setText(name);
        customersVoen.setText(voen);
        customerType.setSelectedItem(typeLabel);
    }//GEN-LAST:event_customersTableMouseClicked

    private void customersDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersDeleteButtonActionPerformed
        CustomersDao dao=new CustomersDao();
        try {
            dao.deleteCustomer(id(), name(), voen(), type());
        } catch (SQLException ex) {
            Logger.getLogger(CustomerController.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel model=(DefaultTableModel)customersTable.getModel();
        model.setRowCount(0);
        addContents();
    }//GEN-LAST:event_customersDeleteButtonActionPerformed

    private void searchCustomerByVoenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerByVoenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchCustomerByVoenActionPerformed

    private void searchCustomerByTypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchCustomerByTypeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_searchCustomerByTypeFocusGained

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        String name=searchCustomerByName.getText();
        String voen=searchCustomerByVoen.getText();
        Integer type=searchCustomerByType.getSelectedIndex()+1;
        DefaultTableModel model=(DefaultTableModel)customersTable.getModel();
        model.setRowCount(0);
        addSelectedContents(name, voen, type);
        
    }//GEN-LAST:event_searchButtonMouseClicked

    private void customerTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerTypeActionPerformed

    private void searchCustomerByTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerByTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchCustomerByTypeActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        DefaultTableModel model=(DefaultTableModel)customersTable.getModel();
        model.setRowCount(0);
        addContents();
    }//GEN-LAST:event_jButton1MouseClicked

    private void backButtonFromCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonFromCustomersMouseClicked
        ManagementController open=new ManagementController();
        open.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonFromCustomersMouseClicked

    private void backButtonFromCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonFromCustomersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonFromCustomersActionPerformed
    private Integer id(){
        DefaultTableModel model=(DefaultTableModel)customersTable.getModel();
        int row=customersTable.getSelectedRow();
        Integer id=(Integer)model.getValueAt(row, 0);
        return id;
    }
    private String name(){
       String name=customerName.getText();
       return name;
    } 
    private String voen(){
       String voen=customersVoen.getText();
       return voen;
    }
    private Integer type(){
        Integer type=customerType.getSelectedIndex()+1;
        return type;
    }
    private void addComboData(){
        DictionaryDao dao=new DictionaryDao();
        try {
            List<String> dics=dao.dictonaryContents(DictionaryEnum.CUSTOMER_TYPE.getKey());
            for(String e : dics){
                customerType.addItem(e);
                searchCustomerByType.addItem(e);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    private void addContents(){
        CustomersDao dao=new CustomersDao();
        try {
            List<Customers> customersList=dao.customersTableContents();
            DefaultTableModel customersTb=(DefaultTableModel)customersTable.getModel();
            Object columns[]=new Object[4];
            for(Customers e:customersList){
                columns[0]=e.getId();
                columns[1]=e.getName();
                columns[2]=e.getVoen();
                columns[3]=e.getTypeLabel();
                Integer existence=e.getExistence();
                if(existence==1) customersTb.addRow(columns);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerController.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    private void addSelectedContents(String name,String voen,Integer type){
        CustomersDao dao=new CustomersDao();
        try {
            List<Customers> customersList=dao.selectedCustomers(name, voen, type);
            DefaultTableModel customersTb=(DefaultTableModel)customersTable.getModel();
            Object columns[]=new Object[4];
            for(Customers e:customersList){
                columns[0]=e.getId();
                columns[1]=e.getName();
                columns[2]=e.getVoen();
                columns[3]=e.getTypeLabel();
                Integer existence=e.getExistence();
                if(existence==1) customersTb.addRow(columns);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerController.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
                  UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Type;
    private javax.swing.JLabel Voen;
    private javax.swing.JButton backButtonFromCustomers;
    private javax.swing.JTextField customerName;
    private javax.swing.JLabel customerNameSearch;
    private javax.swing.JComboBox<String> customerType;
    private javax.swing.JLabel customerTypeSearch;
    private javax.swing.JLabel customerVoenSearch;
    private javax.swing.JButton customersDeleteButton;
    private javax.swing.JButton customersInsertButton;
    private javax.swing.JTable customersTable;
    private javax.swing.JButton customersUpdateButton;
    private javax.swing.JTextField customersVoen;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchCustomerByName;
    private javax.swing.JComboBox<String> searchCustomerByType;
    private javax.swing.JTextField searchCustomerByVoen;
    // End of variables declaration//GEN-END:variables
}
