/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package az.com.salesmanagement.controller;

import az.com.salesmanagement.dao.ProductsDao;
import az.com.salesmanagement.model.Products;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vafa
 */
public class ProductsController extends javax.swing.JFrame {

    /**
     * Creates new form ProductsController
     */
    public ProductsController() {
        initComponents();
        addContents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        productNameSearch = new javax.swing.JLabel();
        searchProductsByName = new javax.swing.JTextField();
        searchProductsByPrice = new javax.swing.JTextField();
        productPriceSearch = new javax.swing.JLabel();
        productStockCountSearch = new javax.swing.JLabel();
        SearchButtonProducts = new javax.swing.JButton();
        searchProductsByStockCount = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        productsUpdateButton = new javax.swing.JButton();
        productsDeleteButton = new javax.swing.JButton();
        productsİnsertButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        productName = new javax.swing.JTextField();
        productPrice = new javax.swing.JTextField();
        productsStockCount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        backButtonFromProducts = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(12, 102, 193));

        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ad", "Qiymət", "Miqdar"
            }
        ));
        productsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productsTable);

        jPanel2.setBackground(new java.awt.Color(12, 102, 193));

        productNameSearch.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        productNameSearch.setForeground(new java.awt.Color(240, 248, 255));
        productNameSearch.setText("Ad");

        searchProductsByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProductsByNameActionPerformed(evt);
            }
        });

        productPriceSearch.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        productPriceSearch.setForeground(new java.awt.Color(240, 248, 255));
        productPriceSearch.setText("Qiymət");

        productStockCountSearch.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        productStockCountSearch.setForeground(new java.awt.Color(240, 248, 255));
        productStockCountSearch.setText("Miqdar");

        SearchButtonProducts.setBackground(new java.awt.Color(240, 248, 255));
        SearchButtonProducts.setFont(new java.awt.Font("Nyala", 1, 18)); // NOI18N
        SearchButtonProducts.setForeground(new java.awt.Color(12, 102, 193));
        SearchButtonProducts.setText("Axtarın");
        SearchButtonProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchButtonProductsMouseClicked(evt);
            }
        });
        SearchButtonProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonProductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchProductsByName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchProductsByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productPriceSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productStockCountSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchProductsByStockCount, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(SearchButtonProducts)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productPriceSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productStockCountSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchProductsByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchProductsByName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchProductsByStockCount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(SearchButtonProducts))
        );

        jPanel3.setBackground(new java.awt.Color(12, 102, 193));

        productsUpdateButton.setBackground(new java.awt.Color(240, 248, 255));
        productsUpdateButton.setFont(new java.awt.Font("Nyala", 1, 24)); // NOI18N
        productsUpdateButton.setForeground(new java.awt.Color(12, 102, 193));
        productsUpdateButton.setText("Dəyiş");
        productsUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsUpdateButtonActionPerformed(evt);
            }
        });

        productsDeleteButton.setBackground(new java.awt.Color(240, 248, 255));
        productsDeleteButton.setFont(new java.awt.Font("Nyala", 1, 24)); // NOI18N
        productsDeleteButton.setForeground(new java.awt.Color(12, 102, 193));
        productsDeleteButton.setText("Sil");
        productsDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsDeleteButtonActionPerformed(evt);
            }
        });

        productsİnsertButton.setBackground(new java.awt.Color(240, 248, 255));
        productsİnsertButton.setFont(new java.awt.Font("Nyala", 1, 24)); // NOI18N
        productsİnsertButton.setForeground(new java.awt.Color(12, 102, 193));
        productsİnsertButton.setText("Əlavə et");
        productsİnsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsİnsertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(productsİnsertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productsDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productsUpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(productsİnsertButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(productsUpdateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(productsDeleteButton)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(12, 102, 193));

        jLabel1.setFont(new java.awt.Font("Nyala", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 248, 255));
        jLabel1.setText("Qiymət");

        jLabel2.setFont(new java.awt.Font("Nyala", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 248, 255));
        jLabel2.setText("Miqdar");

        jLabel3.setFont(new java.awt.Font("Nyala", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 248, 255));
        jLabel3.setText("Ad");

        productName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        productName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameActionPerformed(evt);
            }
        });

        productPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        productPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productPriceActionPerformed(evt);
            }
        });

        productsStockCount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        productsStockCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsStockCountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addComponent(productsStockCount))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(productPrice)))
                .addGap(35, 35, 35))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(productPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(productsStockCount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(240, 248, 255));
        jButton1.setFont(new java.awt.Font("Nyala", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(12, 102, 193));
        jButton1.setText("<-");
        jButton1.setToolTipText("");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        backButtonFromProducts.setBackground(new java.awt.Color(240, 248, 255));
        backButtonFromProducts.setFont(new java.awt.Font("Nyala", 1, 18)); // NOI18N
        backButtonFromProducts.setForeground(new java.awt.Color(12, 102, 193));
        backButtonFromProducts.setText("Geri");
        backButtonFromProducts.setToolTipText("");
        backButtonFromProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonFromProductsMouseClicked(evt);
            }
        });
        backButtonFromProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonFromProductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButtonFromProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(backButtonFromProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchProductsByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProductsByNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchProductsByNameActionPerformed

    private void productNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameActionPerformed

    private void productPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productPriceActionPerformed

    private void productsStockCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsStockCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productsStockCountActionPerformed

    private void productsİnsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsİnsertButtonActionPerformed
        try {
            dao.insertProducts(name(), price(), StockCount());
            DefaultTableModel model=(DefaultTableModel)productsTable.getModel();
            model.setRowCount(0);
            addContents();
        } catch (SQLException ex) {
            Logger.getLogger(ProductsController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_productsİnsertButtonActionPerformed

    private void productsUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsUpdateButtonActionPerformed
        try {
            dao.updateProducts(id(),name(), price(), StockCount());
        } catch (Exception e) {
        }
        DefaultTableModel model=(DefaultTableModel)productsTable.getModel();
        model.setRowCount(0);
        addContents();
    }//GEN-LAST:event_productsUpdateButtonActionPerformed

    private void SearchButtonProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchButtonProductsMouseClicked
        String name=searchProductsByName.getText();
        Double price=null;
        if (searchProductsByPrice.getText()!=null && !searchProductsByPrice.getText().trim().isEmpty()) {
            price = Double.parseDouble(searchProductsByPrice.getText());
        }
        Integer stockCount=null;
        if (searchProductsByStockCount.getText()!=null && !searchProductsByStockCount.getText().trim().isEmpty()) {
            stockCount = Integer.parseInt(searchProductsByStockCount.getText());
        }
        DefaultTableModel model=(DefaultTableModel)productsTable.getModel();
        model.setRowCount(0);
        addSelectedContents(name, price, stockCount);
    }//GEN-LAST:event_SearchButtonProductsMouseClicked

    private void productsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsTableMouseClicked
        DefaultTableModel model=(DefaultTableModel)productsTable.getModel();
        int row=productsTable.getSelectedRow();
        String name=(String) model.getValueAt(row, 1);
        Object price=model.getValueAt(row, 2);
        Object stockCount=model.getValueAt(row, 3);
        productName.setText(name);
        productPrice.setText(price.toString());
        productsStockCount.setText(stockCount.toString());
    }//GEN-LAST:event_productsTableMouseClicked

    private void SearchButtonProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonProductsActionPerformed
        
    }//GEN-LAST:event_SearchButtonProductsActionPerformed

    private void productsDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsDeleteButtonActionPerformed
        try {
            dao.deleteProducts(name(), price(), StockCount());
        } catch (SQLException ex) {
            Logger.getLogger(ProductsController.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel model=(DefaultTableModel)productsTable.getModel();
        model.setRowCount(0);
        addContents();
    }//GEN-LAST:event_productsDeleteButtonActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        DefaultTableModel model=(DefaultTableModel)productsTable.getModel();
        model.setRowCount(0);
        addContents();
    }//GEN-LAST:event_jButton1MouseClicked

    private void backButtonFromProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonFromProductsMouseClicked
        ManagementController open=new ManagementController();
        open.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonFromProductsMouseClicked

    private void backButtonFromProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonFromProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonFromProductsActionPerformed

    ProductsDao dao=new ProductsDao();
    private void addContents(){
        try {
            DefaultTableModel productsTb=(DefaultTableModel)productsTable.getModel();
            List<Products> products=dao.products();
            Object columns[]=new Object[4];
            for(Products e: products){
                columns[0]=e.getId();
                columns[1]=e.getName();
                columns[2]=e.getPrice();
                columns[3]=e.getStockCount();
                if(e.getExistence()==1) productsTb.addRow(columns);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ProductsController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void addSelectedContents(String name,Double price,Integer stockCount){
        try {
            DefaultTableModel productsTb=(DefaultTableModel)productsTable.getModel();
            List<Products> products=dao.selectedProducts(name, price, stockCount);
            Object columns[]=new Object[4];
            for(Products e: products){
                columns[0]=e.getId();
                columns[1]=e.getName();
                columns[2]=e.getPrice();
                columns[3]=e.getStockCount();
                if(e.getExistence()==1) productsTb.addRow(columns);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ProductsController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private Integer id(){
        DefaultTableModel model=(DefaultTableModel)productsTable.getModel();
        int row=productsTable.getSelectedRow();
        Integer id=(Integer) model.getValueAt(row, 0);
        return id;
    }
    private String name(){
        String name=productName.getText();
        return name;
    }
    private double price(){
        double price=Double.parseDouble(productPrice.getText());
        return price;
    }
    private Integer StockCount(){
        Integer stockCount=Integer.parseInt(productsStockCount.getText());
        return stockCount;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
                  UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductsController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductsController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductsController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductsController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductsController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchButtonProducts;
    private javax.swing.JButton backButtonFromProducts;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField productName;
    private javax.swing.JLabel productNameSearch;
    private javax.swing.JTextField productPrice;
    private javax.swing.JLabel productPriceSearch;
    private javax.swing.JLabel productStockCountSearch;
    private javax.swing.JButton productsDeleteButton;
    private javax.swing.JTextField productsStockCount;
    private javax.swing.JTable productsTable;
    private javax.swing.JButton productsUpdateButton;
    private javax.swing.JButton productsİnsertButton;
    private javax.swing.JTextField searchProductsByName;
    private javax.swing.JTextField searchProductsByPrice;
    private javax.swing.JTextField searchProductsByStockCount;
    // End of variables declaration//GEN-END:variables
}
